export const DEFAULT_CHECKLISTS = {
  both_agents: [
    { text: "Create and email escrow timeline to other agent and Bill/Megan", timing: "ASAP", done: false },
    { text: "Send intro email with escrow timeline, available disclosures, and fully executed contract to Sellers/Buyers", timing: "ASAP", done: false },
    { text: "Set up reminders for important dates (3 days prior on Outlook calendar for Bill and Megan)", timing: "ASAP", done: false },
    { text: "Enter contacts and purchase contract into Skyslope", timing: "ASAP", done: false },
    { text: "PDF MLS All Fields Detail and add to Skyslope", timing: "ASAP", done: false },
  ],
  selling_agent: [
    { text: "Open Escrow with client info, commission, agent/TC info and ask for wiring instructions", timing: "ASAP", done: false },
    { text: "Order Inspections (home, pest, mold, radon etc.)", timing: "ASAP", done: false },
    { text: "Confirm utilities are on and access doors unlocked for inspections", timing: "Before inspections", done: false },
    { text: "Confirm status of BMP Certificate", timing: "With Disclosures", done: false },
    { text: "Confirm Sewer Clearance - request clearance certif. (CA Only)", timing: "With Disclosures", done: false },
    { text: "Send Buyer reminder & Wire Instructions for Increase Deposit", timing: "3 days prior", done: false },
    { text: "Confirm Water Heater Bracing", timing: "Prior to appraiser", done: false },
    { text: "Confirm Smoke Detectors and Carbon Monoxide Detectors with seller", timing: "Prior to appraiser", done: false },
    { text: "Email Disclosures to buyer", timing: "Once Received", done: false },
    { text: "DocuSign Disclosures prior to inspection contingency release", timing: "Prior to CR", done: false },
    { text: "Email Buyer reminder to transfer utilities / inquire about 1st visit", timing: "5 days prior", done: false },
    { text: "Ask for and review closing statements from Escrow - double check inspector invoices", timing: "5 days prior", done: false },
    { text: "Order Home Warranty per contract", timing: "5 days prior", done: false },
    { text: "DocuSign Receipt for Reports & Verification of Property Condition", timing: "5 days prior", done: false },
    { text: "Confirm utilities have been transferred", timing: "1 day prior", done: false },
    { text: "Purchase gift for buyer", timing: "Prior to arrival", done: false },
    { text: "Prep house for 1st arrival", timing: "Prior to arrival", done: false },
    { text: "Complete RE Trans. in Skyslope (DRE Auditing)", timing: "Prior to COE", done: false },
  ],
  listing_agent: [
    { text: "Update MLS", timing: "ASAP", done: false },
    { text: "Contact Escrow with client info, commissions, and agent/TC info", timing: "ASAP", done: false },
    { text: "Order NHD (check with Escrow officer before ordering) (CA Only)", timing: "ASAP", done: false },
    { text: "Confirm Sewer Clearance / Order Test with Tapco (CA only)", timing: "ASAP", done: false },
    { text: "Email Disclosures - TDS, SPQ, Lead Based Paint (if required) to seller", timing: "ASAP", done: false },
    { text: "Confirm status of BMP Certificate", timing: "With disclosures", done: false },
    { text: "Confirm utilities are on and access doors unlocked for inspections", timing: "Before inspections", done: false },
    { text: "DocuSign Remaining Disclosures to Seller", timing: "Within 5 days", done: false },
    { text: "Fwd signed Disclosure pkg to Selling Agent", timing: "Within 7 days", done: false },
    { text: "Confirm Water Heater Bracing", timing: "Prior to appraiser", done: false },
    { text: "Confirm Smoke Detectors and Carbon Monoxide Detectors", timing: "Prior to appraiser", done: false },
    { text: "Email Seller asking for utility info", timing: "7 days prior", done: false },
    { text: "Order Home Warranty per contract", timing: "5 days prior", done: false },
    { text: "Provide copies of fully executed docs to client (Listing Agreement, Purchase Contract, Disclosure Pkg)", timing: "5 days prior", done: false },
    { text: "Schedule Carpet / Home cleans if necessary", timing: "Prior to COE", done: false },
    { text: "Seller to cancel utilities", timing: "5 days prior", done: false },
    { text: "Confirm utilities have been canceled", timing: "1 day prior", done: false },
    { text: "Ask for and review closing statements from Escrow - double check inspector invoices", timing: "5 days prior", done: false },
    { text: "Complete RE Trans. in Skyslope (DRE Auditing)", timing: "Prior to COE", done: false },
  ],
  coe: [
    { text: "Email Escrow Officer - Status Check", timing: "At COE", done: false },
    { text: "Confirm all credits are forwarded to Escrow", timing: "At COE", done: false },
    { text: "Send Commission Demand", timing: "At COE", done: false },
    { text: "Review Settlement Statement", timing: "At COE", done: false },
    { text: "Get Final Statement and FIRPTA from Escrow", timing: "At COE", done: false },
    { text: "Complete RE Trans. in Skyslope (DRE Auditing)", timing: "Prior to COE", done: false },
    { text: "Send Bill's Zillow review request email", timing: "After COE", done: false },
    { text: "Add sale to Bill's Zillow profile", timing: "After COE", done: false },
    { text: "Email Nadia copy of Final Closing Statement", timing: "After COE", done: false },
  ],
}

export const DEFAULT_LISTING_CHECKLISTS = {
  megan: [
    { text: "Upload to MLS with floor plans and HOA info (Tahoe Sierra / Incline Village / Northern Nevada)", timing: "ASAP", done: false },
    { text: "Add to Member News", timing: "ASAP", done: false },
    { text: "Email team about new listing and any status changes", timing: "ASAP", done: false },
    { text: "Schedule broker tour", timing: "ASAP", done: false },
    { text: "Update MLS with status changes", timing: "Ongoing", done: false },
    { text: "Update public remarks on MLS periodically", timing: "Ongoing", done: false },
    { text: "Check and update rental dates in MLS every 2 weeks", timing: "Every 2 weeks", done: false },
    { text: "Collect and log showing feedback", timing: "After showings", done: false },
    { text: "Collect and log agent inquiry feedback", timing: "Ongoing", done: false },
    { text: "Send MLS links to seller", timing: "At listing", done: false },
    { text: "Send updates to sellers", timing: "Ongoing", done: false },
    { text: "Implement / respond to seller feedback", timing: "Ongoing", done: false },
    { text: "Review Skyslope documents", timing: "Ongoing", done: false },
  ],
  diana: [
    { text: "Put up sign (check listing agreement)", timing: "ASAP", done: false },
    { text: "Schedule maintenance", timing: "ASAP", done: false },
    { text: "Blow deck", timing: "Pre-listing", done: false },
    { text: "Smoke detectors / CO detectors / water heater bracing", timing: "Pre-listing", done: false },
    { text: "Get mailing address of sellers and add to Bigin", timing: "ASAP", done: false },
    { text: "Install Supra lockbox (check listing agreement)", timing: "ASAP", done: false },
    { text: "TLUXP key tag with seller name on key set", timing: "ASAP", done: false },
    { text: "Schedule cleaning, staging, and maintenance prior to photos", timing: "Pre-photos", done: false },
    { text: "Check and order sewer clearance / backflow test", timing: "Pre-listing", done: false },
    { text: "Schedule defensible space inspection", timing: "Pre-listing", done: false },
    { text: "Check pier and buoy lease", timing: "Pre-listing", done: false },
    { text: "Pull TRPA records, site plan, land verification", timing: "Pre-listing", done: false },
    { text: "Check for open building permits with County, TRPA, and PUD", timing: "Pre-listing", done: false },
    { text: "Schedule repairs and maintenance", timing: "Pre-listing", done: false },
    { text: "Send invoices to seller", timing: "As received", done: false },
    { text: "Add to property showing sheet", timing: "At listing", done: false },
    { text: "Create HomeLight link", timing: "At listing", done: false },
    { text: "Create OneDrive folder under Current Listings", timing: "At listing", done: false },
  ],
  chaney: [
    { text: "Send intro email within 48 hours of signed agreement", timing: "Within 48 hrs", done: false },
    { text: "Email executed listing agreement to seller", timing: "ASAP", done: false },
    { text: "Add to Skyslope", timing: "ASAP", done: false },
    { text: "Send disclosures to sellers (SPQ & TDS via Glide)", timing: "ASAP", done: false },
    { text: "Complete the AVID", timing: "Pre-listing", done: false },
    { text: "Schedule any inspections", timing: "Pre-listing", done: false },
    { text: "Get exclusions list from seller", timing: "Pre-listing", done: false },
  ],
}
